# Generated by Django 4.2.4 on 2023-08-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='preview_url',
        ),
        migrations.AddField(
            model_name='news',
            name='preview',
            field=models.ImageField(default='dasdas', upload_to='', verbose_name='images/news/previews'),
            preserve_default=False,
        ),
    ]
