# Generated by Django 4.2.4 on 2023-08-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_news_preview_url_news_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='preview',
            field=models.ImageField(upload_to='images/news/previews'),
        ),
    ]
