# Generated by Django 4.2.4 on 2023-08-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date name '),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True, verbose_name='News description'),
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(max_length=200, verbose_name='News name'),
        ),
        migrations.AlterField(
            model_name='news',
            name='preview',
            field=models.ImageField(upload_to='images/news/previews', verbose_name='Preview'),
        ),
    ]
