# Generated by Django 4.2.4 on 2023-08-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_created_date_alter_news_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='preview',
            field=models.ImageField(upload_to='photos/news/previews', verbose_name='Preview'),
        ),
    ]
