# Generated by Django 4.2.4 on 2023-08-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_innercategory_preview_alter_innercategory_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innercategory',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='photos/inner_categories'),
        ),
    ]
